---
- name: Configure Pi
  hosts: all
  become: yes
  tasks:
    - name: Update package list and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Copy cmdline.txt
      copy:
        src: ./cmdline.txt
        dest: /boot/cmdline.txt

    - name: Ensure dependencies
      apt:
        name:
          - curl
        state: present

- name: Setup Master
  hosts: master
  become: yes
  tasks:
    - name: Check if K3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_installed

    - name: Download and run install script
      shell: |
        curl -sfL https://get.k3s.io | sh -
      when: not k3s_installed.stat.exists
