---
- name: Configure Pi
  hosts: all
  become: yes
  tasks:
    - name: Update package list and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Copy cmdline.txt
      copy:
        src: ./cmdline.txt
        dest: /boot/cmdline.txt

    - name: Ensure dependencies
      apt:
        name:
          - curl
        state: present

- name: Setup Master
  hosts: master
  become: yes
  tasks:
    - name: Check if K3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_installed

    - name: Download and run install script for K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      when: not k3s_installed.stat.exists

    - name: Retrieve K3S node token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

- name: Setup Agents
  hosts: agents
  become: yes
  tasks:
    - name: Check if K3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_installed

    - name: Join node to K3s cluster
      shell: |
        export K3S_URL=https://{{ hostvars['master']['ansible_host'] }}:6443
        export K3S_TOKEN={{ hostvars['master']['k3s_token']['content'] | b64decode }}
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
      register: k3s_install
      changed_when: "'Already installed' not in k3s_install.stdout"

- name: Install Longhorn on all nodes (if not already installed)
  hosts: all
  become: yes
  tasks:
    - name: Check if Longhorn is already installed
      kubectl:
        command: get pod -n longhorn-system
      register: longhorn_installed
      failed_when: false

    - name: Apply Longhorn deployment if not installed
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.3/deploy/longhorn.yaml
      when: longhorn_installed.failed
      notify:
        - Wait for Longhorn to be ready

- name: Wait for Longhorn to be ready
  hosts: all
  become: yes
  tasks:
    - name: Wait for Longhorn pods to be ready
      wait_for:
        port: 9443
        host: "{{ ansible_host }}"
        state: started
        delay: 10
        timeout: 300

