---
- name: Teardown K3S Cluster
  hosts: k3s_cluster
  become: true
  gather_facts: false

  roles:
    - role: uninstall_k3s
    # - role: wipe_ssd  # Uncomment if you want to fully wipe the SSD rootfs (DESTROYS OS)
