- name: Create ArgoCD namespace
  shell: |
    kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
  args:
    executable: /bin/bash

- name: Install ArgoCD using upstream manifest
  ansible.builtin.shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  args:
    executable: /bin/bash
  run_once: true
